EdtechSim/Pages/CourseDetail.cshtml.cs
using Core.EdTech.Domain.DataAccess.Interfaces;
using Core.EdTech.Domain.Entities;
using Core.EdTech.Domain.Entities.Identity;
using Core.EdTech.Domain.ViewModels;
using Core.EdTech.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EdtechSim.Pages
{
  [Authorize]
  public class CourseDetailModel : PageModel
  {
    private readonly ICourseManagementService _courseManagementService;
    private readonly IUnitOfWork<UserProfile> unitOfWork;
    private readonly UserManager<ApplicationUser> userManager;
    private readonly IRWLService rWLService;

    public CourseDetailModel(ICourseManagementService courseManagementService, IUnitOfWork<UserProfile> unitOfWork, UserManager<ApplicationUser> userManager, IRWLService rWLService)
    {
      _courseManagementService = courseManagementService;
      this.unitOfWork = unitOfWork;
      this.userManager = userManager;
      this.rWLService = rWLService;
    }

    public UserProfile UserProfile { get; set; }

    [BindProperty]
    public Guid CourseId { get; set; }
    public Course? Course { get; set; }
    public async Task<IActionResult> OnGetAsync(Guid Id)
    {
      Course = await _courseManagementService.GetCourse(Id);
      return Page();
    }

    public async Task<IActionResult> OnPostGetDiscount()
    {
      var user = await userManager.GetUserAsync(User);
      UserProfile = unitOfWork.Repository.Get(x => x.Email == user.Email).FirstOrDefault();
      if(UserProfile.RwlMemberId == null)
      {
        UserProfile.RwlMemberId = (await rWLService.Initialize(new RWLUserDetail
        {
          FirstName = UserProfile.FirstName,
          LastName = UserProfile.LastName,
          Email = UserProfile.Email,
          PhoneNumber = UserProfile.PhoneNumber
        })).Data.RwlMemberId;

        unitOfWork.Repository.Update(UserProfile);
        await unitOfWork.SaveAsync();
      }
      return RedirectToPage("/DiscountProvider", new { Id = CourseId});
    }
  }
}

EdtechSim/Pages/CourseManagement.cshtml.cs
using Core.EdTech.Domain.Entities;
using Core.EdTech.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EdtechSim.Pages
{
  [Authorize]
  public class CourseManagementModel : PageModel
  {
    private readonly ICourseManagementService courseManagementService;
    private readonly ILogger<CourseManagementModel> logger;
    public List<Course> CourseList { get; set; }
    [BindProperty]
    public Course AddCourse { get; set; }

    public CourseManagementModel(ICourseManagementService courseManagementService, ILogger<CourseManagementModel> logger)
    {
      this.courseManagementService = courseManagementService;
      this.logger = logger;
    }

    public async Task<IActionResult> OnGetAsync()
    {
      CourseList = await courseManagementService.GetCourses();
      return Page();
    }

    public async Task<IActionResult> OnPostAddCourse()
    {
      logger.LogWarning("Beginning Add course function");
      await courseManagementService.AddCourse(AddCourse);
      return RedirectToPage();
    }
  }
}

EdtechSim/Pages/DiscountProvider.cshtml.cs
using Core.EdTech.Domain.DataAccess.Interfaces;
using Core.EdTech.Domain.Entities;
using Core.EdTech.Domain.Entities.Identity;
using Core.EdTech.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EdtechSim.Pages
{
  public class DiscountProviderModel : PageModel
  {
    private readonly ICourseManagementService _courseManagementService;
    private readonly IUnitOfWork<UserProfile> unitOfWork;
    private readonly UserManager<ApplicationUser> userManager;
    private readonly IRWLService rWLService;

    public DiscountProviderModel(ICourseManagementService courseManagementService, IUnitOfWork<UserProfile> unitOfWork, UserManager<ApplicationUser> userManager, IRWLService rWLService)
    {
      _courseManagementService = courseManagementService;
      this.unitOfWork = unitOfWork;
      this.userManager = userManager;
      this.rWLService = rWLService;
    }

    public List<SelectListItem> ServiceProviderList { get; set; } = new List<SelectListItem>();
    public Course? Course { get; set; }
    [BindProperty]
    public string DiscountProviderId { get; set; }
    public UserProfile UserProfile { get; set; }
    public async Task<IActionResult> OnGetAsync(Guid Id)
    {
      var user = await userManager.GetUserAsync(User);
      UserProfile = unitOfWork.Repository.Get(x => x.Email == user.Email).FirstOrDefault();
      Course = await _courseManagementService.GetCourse(Id);

      foreach(var item in (await rWLService.GetServiceProviders(UserProfile.RwlMemberId.Value)).Data)
      {
        ServiceProviderList.Add(new SelectListItem {
          Text = item.ServiceProviderName,
          Value = item.ServiceProviderId.ToString()
        });
      }
      return Page();
    }

    public async Task<IActionResult> OnPostComputeDiscount()
    {
      return RedirectToPage();
    }
  }
}

EdtechSim/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace EdtechSim.Pages
{
  [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
  [IgnoreAntiforgeryToken]
  public class ErrorModel : PageModel
  {
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
      _logger = logger;
    }

    public void OnGet()
    {
      RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
  }

}

EdtechSim/Pages/Index.cshtml.cs
using Core.EdTech.Domain.DataAccess.Interfaces;
using Core.EdTech.Domain.Entities;
using Core.EdTech.Domain.Entities.Identity;
using Core.EdTech.Domain.ViewModels;
using Core.EdTech.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EdtechSim.Pages
{
  [Authorize]
  public class IndexModel : PageModel
  {
    private readonly ILogger<IndexModel> _logger;
    private readonly IRWLService _rdfService;
    private readonly IUnitOfWork<UserProfile> unitOfWork;
    private readonly UserManager<ApplicationUser> userManager;
    private readonly ICourseManagementService courseManagementService;

    public List<Course> AllCourses { get; set; }
    public UserProfile UserProfile { get; set; }
    public List<ServiceProviderResponse> ServiceProviderResponses { get; set; }
    public IndexModel(ILogger<IndexModel> logger, IRWLService rdfService, IUnitOfWork<UserProfile> unitOfWork, UserManager<ApplicationUser> userManager, ICourseManagementService courseManagementService)
    {
      _logger = logger;
      _rdfService = rdfService;
      this.unitOfWork = unitOfWork;
      this.userManager = userManager;
      this.courseManagementService = courseManagementService;
    }

    public async Task<IActionResult> OnGetAsync()
    {
      var user = await userManager.GetUserAsync(User);
      UserProfile = unitOfWork.Repository.Get(x => x.Email == user.Email).FirstOrDefault();

      if (UserProfile.RwlMemberId == null)
      {
        UserProfile.RwlMemberId = (await _rdfService.Initialize(new RWLUserDetail
        {
          Email = UserProfile.Email,
          FirstName = UserProfile.FirstName,
          LastName = UserProfile.LastName,
          PhoneNumber = UserProfile.PhoneNumber
        })).Data.RwlMemberId;
      }


      AllCourses = await courseManagementService.GetCourses();
      return Page();
    }
  }
}

EdtechSim/Pages/Login.cshtml.cs
using Core.EdTech.Domain.ViewModels.Authentication;
using Core.EdTech.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EdtechSim.Pages
{
  public class LoginModel : PageModel
    {
        private readonly IAuthenticationService authenticationService;

        public LoginModel(IAuthenticationService authenticationService)
        {
          this.authenticationService = authenticationService;
        }

        [BindProperty]
        public SignInVM? SignInVM { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = "/Index")
        {
            if(SignInVM == null)
            {
                return Page();
            }

            var result = await authenticationService.SignIn(SignInVM, null);
            if(result.Succeeded)
            {
                var user = HttpContext.User;

                return Redirect(returnUrl);
            }
            return Page();
        }
    }
}

EdtechSim/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EdtechSim.Pages
{
  public class PrivacyModel : PageModel
  {
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
      _logger = logger;
    }

    public void OnGet()
    {
    }
  }

}

EdtechSim/Pages/Register.cshtml.cs
using Core.EdTech.Domain.ViewModels.Authentication;
using Core.EdTech.Domain.ViewModels.Mail;
using Core.EdTech.Infrastructure.Helpers.AppSettings;
using Core.EdTech.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EdtechSim.Pages
{
  public class RegisterModel : PageModel
    {
        private readonly ConfigOptions configOptions;
        private readonly IMailService mailService;
        private readonly IAuthenticationService authenticationService;
        public string? ReturnUrl { get; set; }

        public RegisterModel(ConfigOptions configOptions, IMailService mailService, IAuthenticationService authenticationService)
        {
          this.configOptions = configOptions;
          this.mailService = mailService;
          this.authenticationService = authenticationService;
          ReturnUrl = "./EmailConfirmation";
    }

        [BindProperty]
        public RegistrationVM RegistrationVM { get; set; }
        public SignInVM? SignInVM { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(RegistrationVM?.Input == null || RegistrationVM?.UserProfile == null)
            {
                return Page();
            }

            RegistrationVM.UserProfile.Email = RegistrationVM.Input.Email;
            ModelState.ClearValidationState(nameof(RegistrationVM));

            if (TryValidateModel(RegistrationVM, nameof(RegistrationVM)))
            {
              var result = await authenticationService.SignUp(RegistrationVM);

              if (result)
              {
                SignInVM = new SignInVM
                {
                  Email = RegistrationVM.Input.Email,
                  Password = RegistrationVM.Input.Password
                };
              }
              var callbackUrl = await authenticationService.GenerateEmailConfirmationTokenUrl(RegistrationVM.Input.Email, Request.Scheme);
              MailDataVM mailDataVM = new MailDataVM
              {
                EmailToId = RegistrationVM.Input.Email,
                EmailToName = "",
                EmailSubject = "GetOnline Email Confirmation",
                EmailBody = $"Kindly confirm your email at {callbackUrl}"
              };
              await mailService.SendMailAsync(mailDataVM);

              return Redirect(ReturnUrl);
            }

            else
            {
              foreach (var error in ViewData.ModelState.Values.SelectMany(modelState => modelState.Errors))
              {
                string messages = string.Join("; ", ModelState.Values
                                    .SelectMany(x => x.Errors)
                                    .Select(x => x.ErrorMessage));
                Console.WriteLine(messages);
              }
      }
      return Page();
        }
  }
}

EdtechSim/Pages/CourseDetail.cshtml
@page 
@model EdtechSim.Pages.CourseDetailModel
@{
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.ImageUrl)
        </dd>
        <dt class="col-sm-2" >
            <form method="post">
                <input type="submit" class="btn btn-success" value="Buy Course" />
            </form>
        </dt>
        <dd class="col-sm-10">
          <form method="post" asp-page-handler="GetDiscount">
                <input type="hidden" asp-for="CourseId" value="@Model.Course.Id" />
                <input type="submit" class="btn btn-primary" value="Buy Course with RWL Discount" />
          </form>
        </dd>

    </dl>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EdtechSim/Pages/CourseManagement.cshtml
@page
@model EdtechSim.Pages.CourseManagementModel
@{
    ViewData["Title"] = "Home page";
    Layout = "_CourseLayout";
}


<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Manage <b>Courses</b></h2>
                </div>
                <div class="col-sm-6">
                    <a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Add New Employee</span></a>
                    <a href="#deleteEmployeeModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Image URL</th>
                    <th>RWL Code</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

              @foreach(var course in Model.CourseList){
                    <tr>
                        <td>@course.Name</td>
                        <td>@course.Price</td>
                        <td>@course.ImageUrl</td>
                        <td>@course.RwlCode</td>
                        <td>
                            <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                            <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                        </td>
                    </tr>
              }
            </tbody>
        </table>

    </div>
</div>
<!-- Edit Modal HTML -->
<div id="addEmployeeModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" asp-page-handler="AddCourse">
                <div class="modal-header">
                    <h4 class="modal-title">Add Course</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input asp-for="AddCourse.Name" type="text" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Price</label>
                        <input asp-for="AddCourse.Price" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Image URL</label>
                        <textarea asp-for="AddCourse.ImageUrl" class="form-control" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>RWL Code</label>
                        <input asp-for="AddCourse.RwlCode" class="form-control" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-success" value="Add">
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Edit Modal HTML -->
<div id="editEmployeeModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form>
                <div class="modal-header">
                    <h4 class="modal-title">Edit Employee</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <textarea class="form-control" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Phone</label>
                        <input type="text" class="form-control" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-info" value="Save">
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Delete Modal HTML -->
<div id="deleteEmployeeModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form>
                <div class="modal-header">
                    <h4 class="modal-title">Delete Employee</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <input type="hidden" id="toDelete"/>
                <div class="modal-body">
                    <p>Are you sure you want to delete these Records?</p>
                    <p class="text-warning"><small>This action cannot be undone.</small></p>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </div>
            </form>
        </div>
    </div>
</div>

EdtechSim/Pages/DiscountProvider.cshtml
@page
@model EdtechSim.Pages.DiscountProviderModel
@{
}

<div>
    <h4>Choose a discount provider</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.ImageUrl)
        </dd>
        <form method="post" asp-page-handler="ComputeDiscount">
          <dt class="col-sm-2">
            <select asp-for="DiscountProviderId" asp-items="@Model.ServiceProviderList"></select>
          </dt>
          <dd class="col-sm-10">
                  <input type="submit" class="btn btn-primary" value="Compute Discount" />
          </dd>
        </form>
    </dl>
</div>

EdtechSim/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<section class="section-products">
    <div class="container">
        <div class="row">
          @foreach(var course in Model.AllCourses){
                <!-- Single Product -->
                <div class="col-md-6 col-lg-4 col-xl-3">
                    <div id="product-4" class="single-product">
                        <div class="part-1" style="background:url('@course.ImageUrl')">
                            <span class="new">new</span>
                            <ul>
                                <li><a asp-page="CourseDetail" asp-route-Id="@course.Id"><i class="fas fa-expand"></i></a></li>
                            </ul>
                        </div>
                        <div class="part-2">
                            <h3 class="product-title">@course.Name</h3>
                            <h4 class="product-price">$@course.Price</h4>
                        </div>
                    </div>
                </div>
          }

        </div>
    </div>
</section>

EdtechSim/Pages/Login.cshtml
@page
@model EdtechSim.Pages.LoginModel
@{
    Layout = "_AuthLayout";
    ViewData["Title"] = "Sign In";
}

	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="post">
					<span class="login100-form-title">
						Sign In
					</span>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter email">
						<input class="input100" asp-for="SignInVM.Email" placeholder="Email">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Please enter password">
						<input class="input100" asp-for="SignInVM.Password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<div class="text-right p-t-13 p-b-23">
						<span class="txt1">
							Forgot
						</span>

						<a href="#" class="txt2">
							Username / Password?
						</a>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign in
						</button>
					</div>

					<div class="flex-col-c p-t-170 p-b-40">
						<span class="txt1 p-b-9">
							Don’t have an account?
						</span>

						<a asp-page="/Register" class="txt3">
							Sign up now
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	

EdtechSim/Pages/Register.cshtml
@page
@model EdtechSim.Pages.RegisterModel
@{
    Layout = "_AuthLayout";
    ViewData["Title"] = "Sign Up";
}


	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="post">
					<span class="login100-form-title">
						Sign Up
					</span>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter firstname">
						<input class="input100" asp-for="RegistrationVM.UserProfile.FirstName" placeholder="First Name">
						<span class="focus-input100"></span>
					</div>

                <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter lastname">
						<input class="input100" asp-for="RegistrationVM.UserProfile.LastName" placeholder="Last Name">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Please enter password">
						<input class="input100" asp-for="RegistrationVM.Input.Email" placeholder="Email">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Please enter password">
						<input class="input100" asp-for="RegistrationVM.UserProfile.PhoneNumber" placeholder="+234xxxxxxxxxx">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Date of Birth">
						<input class="input100" asp-for="RegistrationVM.UserProfile.DateOfBirth">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Please enter password">
						<input class="input100" asp-for="RegistrationVM.Input.Password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 validate-input m-b-16" data-validate = "Please enter password again">
						<input class="input100" asp-for="RegistrationVM.Input.ConfirmPassword" placeholder="Confirm Password">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign Up
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>